AllCops:
  TargetRubyVersion: 2.3.8
  Exclude:
    - tooling/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/LambdaCall:
  EnforcedStyle: braces

Style/ModuleFunction:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Naming/FileName:
  Exclude:
    - lib/fun-ruby.rb

Style/DocumentationMethod:
  Enabled: true

Style/Documentation:
  Enabled: true
  Exclude:
    - lib/fun_ruby/array/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/TrailingUnderscoreVariable:
  Enabled: false
