AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/LambdaCall:
  EnforcedStyle: braces

Style/ModuleFunction:
  Enabled: false

Layout/LineLength:
  Max: 120
