name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.0
          - 2.7
          - 2.6
          - 2.5
          - 2.4
          - 2.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}

      - name: Install bundler
        run: |
          gem install bundler --no-document
          bundle config set without 'tools benchmarks docs'

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Rubocop
        run: bin/rubocop

      - name: Rspec
        run: bin/rspec

      - name: Doc tests
        run: bin/yard doctest
