name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUNDLE_WITHOUT: development
  
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.2
          - 3.1
          - 3.0
          - 2.7
          - 2.6
          - 2.5
          - 2.4
          - 2.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.133.2
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Rubocop
        run: bin/rubocop

      - name: Rspec
        run: bin/rspec

      - name: Doc tests
        run: bin/yard doctest
